- .gitignore
- LICENSE
- pyproject.toml
this is the basic structure i think we should start from for the repository. django and html frontend can go in frontend. data engineering and ML stuff in backend. the tests folder would house tests for data engineering and ML, a tests.py file is created for individual django apps.
> created initial basic structure for repository

- .github/workflows/lint-test.yml
- CODE_OF_CONDUCT.md
- README.md
- civiclens/data_engineering/access_api_data.py
- civiclens/data_engineering/db_init.sql
- civiclens/manage.py
- civiclens/regulations/admin.py
- civiclens/regulations/apps.py
- civiclens/regulations/models.py
- civiclens/regulations/tests.py
- civiclens/regulations/views.py
- civiclens/tests/test_access_api_data.py
- civiclens/utils/constants.py
- civiclens/website/asgi.py
- civiclens/website/settings.py
- civiclens/website/urls.py
- civiclens/website/wsgi.py
ran `pre-commit run --all-files` to clean up linting
> ran pre-commit on all files

- civiclens/website/urls.py
fixed bug (i think) on earlier PR - no substantive changes!
> added include to import statement

- civiclens/data_engineering/access_api_data.py
Just addressing some minor linting issues that were flagged (but I missed) in the last PR
> address flagged ruff issues

- civiclens/regulations/urls.py
- civiclens/regulations/views.py
- civiclens/templates/document.html
I also sent the document and comment info related to the document to document.html and displayed it in an exceedingly basic way.
If someone thinks it would be best to remove changes from document.html, feel free to do so or let me know.
> 74 fixing the regulationsurlspy and regulationsviewspy endpoints

- civiclens/regulations/forms.py
- civiclens/regulations/models.py
- civiclens/regulations/views.py
- civiclens/templates/includes/footer.html
- civiclens/templates/includes/navigation.html
- civiclens/templates/layouts/base.html
- civiclens/templates/search_page.html
- civiclens/templates/search_results.html
MVP implementation of the search results page is complete !
> 44 build search results page

- README.md
Given feedback on our last checkpoint and how we've moved beyond what was in the readme, I've updated aspects about how we're working with the .env file.
> Update readme .env description

- civiclens/collect/move_data_from_api_to_database.py
> fix an import

- civiclens/collect/move_data_from_api_to_database.py
fyi @rezarzky this addresses your issue. You want to call add_comments_to_db_for_existing_doc in a cron job to get new comments for existing documents
> Slight refactor to break out the two different times we access comments via API for a document

- .pre-commit-config.yaml
- civiclens/tests/test_utils.py
- civiclens/utils/database_access.py
- pyproject.toml
- refactored `pull_data` to return lists or dataframes
- add tests for `pull_data`
- created client wrapper for postgres connection
> Refactor sql pull

- civiclens/templates/document.html
- civiclens/templates/home.html
- civiclens/templates/layouts/base.html
- civiclens/templates/search_page.html
- civiclens/templates/search_results.html
finished linting the remainder of the html pages!
> 139 curlylint remaining html pages

- civiclens/tests/test_utils.py
- civiclens/utils/text.py
Let me know if this meets your needs, otherwise happy to re-write the function
> string cleaning funcs

- civiclens/utils/backup_postgres.sh
- civiclens/utils/run_civiclens_update.sh
bash script to backup database and pulling data
> bash script for cron job

- civiclens/regulations/static/js/graph.js
This PR has the changes to Civiclens/civiclens/regulations/static/js/graph.js that were implemented last Friday made there a single figure instead of the duplicated figure on document.html
> Friday's update with Michael to make only a single graph

- civiclens/nlp/pipeline.py
- civiclens/utils/database_access.py
fix `upload_comments` to overwrite rows based on last_updated date
> 213 update sql insert

- civiclens/collect/check_doc_status.py
- civiclens/regulations/views.py
- civiclens/templates/search_page.html
- civiclens/templates/search_results.html
drafted up a new version of the search_page based on our conversation on Friday:
> 219 add content to search landing page

- civiclens/nlp/pipeline.py
Makes sure that a summary exists before creating a title
> fix plain english title bug #241

- civiclens/templates/document.html
added longer padding on the section and i think this solved the issue - not exactly sure why its cutting off, but we can play around with it more when we have the doc page working with the NLP output.
> added longer padding for section

- civiclens/templates/about.html
- civiclens/templates/home.html
> added johns bio and end of home page

- civiclens/nlp/pipeline.py
> fix pipeline update query

- civiclens/templates/about.html
- civiclens/templates/home.html
- civiclens/templates/search_results.html
no accessibility flags on all pages!
> 266 final accessibility audit

- civiclens/regulations/static/js/graph.js
> 275 fix graph issue

- mkdocs.yml
add new endpoint markdowns to yaml, so that they appear on docs site
> add new endpoints to nav

- civiclens/nlp/pipeline.py
docs with existing plain english titles were getting replaced with null titles when the NLP analysis was updated
> create dictionary of doc-titles 
